"""initial migration

Revision ID: 95b67cf3560e
Revises: 
Create Date: 2021-12-17 13:12:29.036496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95b67cf3560e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacies',
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_name', sa.String(length=100), nullable=False),
    sa.Column('pharmacy_email', sa.String(length=100), nullable=False),
    sa.Column('pharmacy_phone', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pharmacy_id'),
    sa.UniqueConstraint('pharmacy_email'),
    sa.UniqueConstraint('pharmacy_name')
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('staff_name', sa.String(length=100), nullable=False),
    sa.Column('staff_dob', sa.String(length=20), nullable=False),
    sa.Column('staff_password', sa.String(length=200), nullable=False),
    sa.Column('staff_is_admin', sa.Boolean(), server_default='False', nullable=False),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_table('contactdetails',
    sa.Column('contactdetails_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('contactdetails_id')
    )
    op.create_table('econtactdetails',
    sa.Column('econtactdetails_id', sa.Integer(), nullable=False),
    sa.Column('contactdetails_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contactdetails_id'], ['contactdetails.contactdetails_id'], ),
    sa.PrimaryKeyConstraint('econtactdetails_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('econtactdetails')
    op.drop_table('contactdetails')
    op.drop_table('staff')
    op.drop_table('pharmacies')
    # ### end Alembic commands ###
