"""initial migration

Revision ID: ffb5a9f9dad0
Revises: 
Create Date: 2021-12-18 12:24:57.619321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb5a9f9dad0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy',
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_name', sa.String(length=100), nullable=False),
    sa.Column('pharmacy_email', sa.String(length=100), nullable=False),
    sa.Column('pharmacy_phone', sa.String(length=20), nullable=False),
    sa.Column('pharmacy_password', sa.String(length=200), nullable=False),
    sa.Column('pharmacy_is_admin', sa.Boolean(), server_default='False', nullable=False),
    sa.PrimaryKeyConstraint('pharmacy_id')
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('staff_name', sa.String(length=100), nullable=False),
    sa.Column('staff_email', sa.String(length=100), nullable=False),
    sa.Column('staff_dob', sa.String(length=100), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['pharmacy.pharmacy_id'], ),
    sa.PrimaryKeyConstraint('staff_id'),
    sa.UniqueConstraint('staff_email'),
    sa.UniqueConstraint('staff_name')
    )
    op.create_table('certificates',
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('certificate_id'),
    sa.UniqueConstraint('staff_id')
    )
    op.create_table('contactdetails',
    sa.Column('contactdetails_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('contactdetails_id'),
    sa.UniqueConstraint('staff_id')
    )
    op.create_table('econtactdetails',
    sa.Column('econtactdetails_id', sa.Integer(), nullable=False),
    sa.Column('contactdetails_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contactdetails_id'], ['contactdetails.contactdetails_id'], ),
    sa.PrimaryKeyConstraint('econtactdetails_id'),
    sa.UniqueConstraint('contactdetails_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('econtactdetails')
    op.drop_table('contactdetails')
    op.drop_table('certificates')
    op.drop_table('staff')
    op.drop_table('pharmacy')
    # ### end Alembic commands ###
